### ISSUE TITLE
Incorrect date if rights expire at the end of year

### ISSUE THREAD

**Issue by marcinszwarc** [Leader-board/userrights-reminder-bot#2]
My rights at Wikimania wiki expire at Jan 1, 2025, 0:00 UTC (exactly as 2024 ends in UTC). However, the bot reported the expiration time in its message as 2025-12-31 00:00:00, which is 364 days past the date.

Bot messages: https://wikimania.wikimedia.org/w/index.php?title=User_talk%3AMsz2001&diff=423627&oldid=402855

**Comment by Leader-board** [comment]
I'm looking at this.

**Comment by Leader-board** [comment]
I think I've fixed this one - apologies for the inconvenience.
